DATASET: 
  TRAIN: 'encoder/outputs/vit_b16_384_fps1/train'
  VAL: 'encoder/outputs/vit_b16_384_fps1/test'
  GT: ''
DATALOADER:
  NUM_WORKERS: 4
INPUT:
  QA: 'qa_maskx-1.pth'
  VIDEO: 'video.pth'
  SCRIPT: 'script.pth'
  DIM: 768
  NUM_MASKS: 1
MODEL:
  ARCH: 'q2a'
  DIM_STATE: 768
  NUM_HEADS: 1
  HISTORY: 
    TRAIN: 'gt'
    VAL: 'max'
    ARCH: 'gru'
SOLVER:
  LR: 0.002
  BATCH_SIZE: 16
  WARMUP_EPOCHS: 1
  MAX_EPOCHS: 6
CHECK_VAL_EVERY_N_EPOCH: 1
NUM_GPUS: 1
CKPT: ''